---

apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: bigip
spec:
  controllerName: f5.io/gateway-controller-name

---

apiVersion: v1
kind: Namespace
metadata:
  name: abcd
  labels:
    resource.zone: allowed-namespaces
